export const LINKS = {
  HOME: "/",
  SIGNIN: "/SignIn",
  SIGNUP: "/SignUp",
  ABOUT: "/About",
  DISCOUNTS: "/Discounts",
  BOOKINGS: "/Bookings",
  SAVED: "/Saved",
  PROFILE: "/Profile",
  LOYALTY: "/Loyalty",
  SEARCH: "/Search",
  RENTING: "/Renting",
  INPROGRESS: "/InProgress",
  MYRENTS: "/MyRents",
};
